apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ts-auth-service
  namespace: ml-train
spec:
  hosts:
  - ts-auth-service
  http:
  - fault:
      delay:
        fixedDelay: 30s
        percentage:
          value: 100
    route:
    - destination:
        host: ts-auth-service
  - route:
    - destination:
        host: ts-auth-service
